### ISSUE TITLE
datasource as environment variables

### ISSUE THREAD

**Issue by jeefo** [KardonskyRoman/ConclusionGeneratorPublic#1]
hello

is it possible to provide data source credentials via ENV variables  in future releases? editing .jar looks pretty much awful this days.

thank you

**Comment by KardonskyRoman** [comment]
sure, it is possible.

**Comment by KardonskyRoman** [comment]
The question is, why do you need this project as it was created for particular users.

**Comment by jeefo** [comment]
> The question is, why do you need this project as it was created for particular users.

Алексей из Ремарка, когда просит обновить ПО, занимает лишнее время...

**Comment by KardonskyRoman** [comment]
will be done soon
